postman/urls.py
from django.views.generic.simple import direct_to_template
from django.conf.urls.defaults import *
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max 
--------------
Views supporting the parameter are: ``write``, ``reply``.
Example::
    ..., {'max': 3}, name='postman_write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``write``, ``reply``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ..., {'user_filter': my_user_filter}, name='postman_write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``write``, ``reply``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ..., {'exchange_filter': my_exchange_filter}, name='postman_write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``write``, ``reply``.
Examples::
    ..., {'autocomplete_channels': (None,'anonymous_ac')}, name='postman_write'),
    ..., {'autocomplete_channels': 'write_ac'}, name='postman_write'),
    ..., {'autocomplete_channel': 'reply_ac'}, name='postman_reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``write``, ``reply``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ..., {'auto_moderators': (mod1, mod2)}, name='postman_write'),
    ..., {'auto_moderators': mod1}, name='postman_reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ..., {'form_classes': (MyCustomWriteForm, MyCustomAnonymousWriteForm)}, name='postman_write'),
    ..., {'form_class': MyCustomFullReplyForm}, name='postman_reply'),
    ..., {'form_class': MyCustomQuickReplyForm}, name='postman_view'),
    ..., {'template_name': 'my_custom_view.html'}, name='postman_view'),
    ..., {'success_url': 'postman_inbox'}, name='postman_reply'),
    ..., {'formatters': (format_subject,format_body)}, name='postman_reply'),
    ..., {'formatters': (format_subject,format_body)}, name='postman_view'),

"""
try:
    from django.conf.urls import patterns, include, url # django 1.4
except ImportError:
    from django.conf.urls.defaults import patterns, include, url # django 1.3
from django.views.generic.simple import redirect_to

OPTION_MESSAGES = 'm'
OPTIONS = OPTION_MESSAGES

urlpatterns = patterns(
    'postman.views',
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', 'inbox', name='postman_inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', 'sent', name='postman_sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', 'archives', name='postman_archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', 'trash', name='postman_trash'),
    url(r'^write/(?:(?P<recipients>[\w.@+-:]+)/)?$', 'write', name='postman_write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', 'reply', name='postman_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', 'view', name='postman_view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', 'view_conversation', name='postman_view_conversation'),
    url(r'^archive/$', 'archive', name='postman_archive'),
    url(r'^delete/$', 'delete', name='postman_delete'),
    url(r'^undelete/$', 'undelete', name='postman_undelete'),
    (r'^$',             direct_to_template, {'template': 'messaging.html'}),
   # (r'^$', direct_to_template,{'template':"messaging.html"} ),
)

tutablr/urls.py
from dajaxice.core import dajaxice_autodiscover
from django.views.generic.simple import direct_to_template
from django.conf import settings
from tutablr_app.forms import ProfileForm
from tutablr_app.forms import YourRegistrationForm
from registration.views import activate
from registration.views import register
from registration.backends.default import DefaultBackend
from django.conf.urls.defaults import *
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required
admin.autodiscover()
dajaxice_autodiscover()

urlpatterns = patterns('',
	 url(r'^login$','tutablr_app.views.loginAjax'),
	 #url ( r'^calendar/user/(.*)$' , TemplateView . as_view ( template_name = "user_calendar.html" ), name = 'user_calendar' ),
	 url( r'^calendar/user/(?P<cal_id>\d+)/$', 'tutablr_app.views.calendar_view', name='user_calendar'),
	 url( r'^calendar/$', 'tutablr_app.views.calendar_user', name='calendar'),
	 url ( r'^calendar/user_events.json/(?P<cal_id>\d+)/$' , 'tutablr_app.views.user_calendar' , name = 'user_events.json' ),
	 #url ( r'^calendar/$' , login_required(TemplateView . as_view ( template_name = "calendar.html" )), name = 'calendar' ),
     	url ( r'^calendar/events.json/*$' , 'tutablr_app.views.calendar' , name = 'events.json' ),
	 url(r'^contact$',auth_views.login,{'template_name':'contact.html'},name='auth_login'), # home page
	 url(r'^submitContact$','tutablr_app.views.contactFormAjax'),
	 url(r'^get_lock/$', 'tutablr_app.views.get_lock'),
	url(r'^unlock_request/$', 'tutablr_app.views.unlock_request'),
	(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
	url(r'^$',auth_views.login,{'template_name':'index.html'},name='auth_login'), # home page
	url(r'^index$',auth_views.login,{'template_name':'index.html'},name='auth_login'), # home page
	(r'^search/$','tutablr_app.views.tutor_search'),
	#(r'^delete$','tutablr_app.views.delete'),
	#(r'^update$','tutablr_app.views.update'),
	(r'drop_event/(?P<cal_id>\d+)/$','tutablr_app.views.drop_event'),
	(r'^edit_tutor_details/', 'tutablr_app.views.edit_tutoring_subjects'),
	(r'^add_unavailable/$','tutablr_app.views.add_unavailable'),
	(r'^update_unavailable/$','tutablr_app.views.update_unavailable'),
	(r'^delete_unavailable/$','tutablr_app.views.delete_unavailable'),
	(r'^update_booking/(?P<cal_id>\d+)/$','tutablr_app.views.update_booking'),
	(r'^confirm_booking/(?P<cal_id>\d+)/$','tutablr_app.views.confirm_booking'),
	(r'^reject_booking/(?P<cal_id>\d+)/$','tutablr_app.views.reject_booking'),
	(r'^add_booking/(?P<cal_id>\d+)/$','tutablr_app.views.add_booking'),
	(r'^delete_booking/(?P<cal_id>\d+)/$','tutablr_app.views.delete_booking'),
	(r'^update_session/(?P<cal_id>\d+)/$','tutablr_app.views.update_session'),
	(r'^delete_session/(?P<cal_id>\d+)/$','tutablr_app.views.delete_session'),
	('^profiles/edit', 'profiles.views.edit_profile', {'form_class': ProfileForm,}), #remove later
	(r'^profiles/', include('profiles.urls')), # remove later
	 url(r'^admin/', include(admin.site.urls)),
	 url(r'^$',auth_views.login,{'template_name':'index.html'},name='auth_login'),
	 url(r'^index$',auth_views.login,{'template_name':'index.html'},name='auth_login'),	 	
	 url(r'^messages/', include('postman.urls')),
	 url(r'^accounts/profile/', direct_to_template, {'template': 'index.html'}, 'index'),
	 url(r'^accounts/', include('registration.backends.default.urls')),
	url(r'^dashboard$','tutablr_app.views.dashboard'),
	url(r'^reviews$','tutablr_app.views.reviews'),
	url( r'^reviews/users/(?P<cal_id>\d+)/$', 'tutablr_app.views.user_reviews'),
	url(r'^howitworks$',auth_views.login,{'template_name':'howitworks.html'},name='auth_login'),
	################# LOCATION URLS  #################
	url(r'^profile/locations$','tutablr_app.views.location'),
	#url(r'^profile/locations/tutoring/edit$','tutablr_app.views.locationSelector'),
	url(r'^profile/locations/tutoring/add$','tutablr_app.views.locationAddTutoring'),
	url(r'^profile/locations/personal/edit$','tutablr_app.views.locationEditPersonal'),
	################# LOCATION URLS  #################
)

tutablr_app/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets 
from tutablr_app.models import *
from registration.forms import RegistrationForm
from registration.models import RegistrationProfile
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple
from django.forms.extras.widgets import SelectDateWidget

class ProfileForm(ModelForm):
 
	def __init__(self, *args, **kwargs):
		super(ProfileForm, self).__init__(*args, **kwargs)
		try:
			self.fields['email'].initial = self.instance.user.email
			self.fields['first_name'].initial = self.instance.user.first_name
			self.fields['last_name'].initial = self.instance.user.last_name
		except User.DoesNotExist:
			pass
 
	email = forms.EmailField(label="Primary email",help_text='')
	first_name = forms.CharField(label="First name",help_text='')
	last_name = forms.CharField(label="Last name",help_text='')
	class Meta:
	  model = UserProfile
	  exclude = ('user',)        
 
	def save(self, *args, **kwargs):
		"""
		Update the primary email address on the related User object as well.
		"""
		u = self.instance.user
		u.email = self.cleaned_data['email']
		u.first_name = self.cleaned_data['first_name']
		u.last_name = self.cleaned_data['last_name']
		u.save()
		profile = super(ProfileForm, self).save(*args,**kwargs)
		return profile

class YourRegistrationForm(RegistrationForm):
	def save(self, profile_callback=None):
		new_user = RegistrationProfile.objects.create_inactive_user(username=self.cleaned_data['username'],
		password=self.cleaned_data['password1'],
		email = self.cleaned_data['email'], 
		first_name = self.cleaned_data['first_name'], 
		last_name=self.cleaned_data['last_name'])
		new_user.save()
		new_profile = Profile(user=new_user)
		new_profile.save()
		return new_user

		
class addBookingForm(forms.Form):
	#print('HERHEHRHERHEHRHRRH')
	date = forms.DateField()
	date.widget.format = '%d/%m/%Y'
	date.widget.attrs.update({'class':'datePicker', 'readonly':'true'})
	start_time = forms.TimeField()
	finish_time = forms.TimeField()
	UoS = forms.ChoiceField()
	description = forms.CharField(max_length=56)
	#creator_id = forms.IntegerField()
	def __init__(self, *args, **kwargs):
		tutor_id = kwargs.pop('tutor_id',0)
		super(addBookingForm, self).__init__(*args, **kwargs)
		choices = [(o.unit_id.unit_id, str(o.unit_id.unit_id)) for o in UnitDetails.objects.filter(user_id = tutor_id, is_tutorable = True)]
		self.fields['UoS'] = forms.ChoiceField(widget = forms.Select(), initial=choices[0][0], choices=choices, required=True)
		#self.fields['creator_id'].widget = forms.HiddenInput()

class searchForm(forms.Form):
        UoS = forms.ChoiceField(label="Unit of Study")
        price_from = forms.IntegerField(label="Price From ($)", initial = 0, required=False)
        price_to = forms.IntegerField(label="Price To ($)", initial=150, required=False)
        distance_choices = [(1000, 'Any'), (5, '5 km'), (10, '10km'), (15, '15km'), (25, '25km')]
        distance = forms.ChoiceField(widget=forms.Select(),initial=distance_choices[4][1],  choices=distance_choices, required=False)
        #only if students
        students_only = forms.BooleanField(label="Students Only")
        rating_from_choices = [(0, 'Any'), (5, '5 Stars'), (4, '4 Stars'), (3, '3 Stars'), (2, '2 Stars'), (1, '1 Star')]
        rating_from = forms.ChoiceField(label="Rating From", widget=forms.Select(), choices=rating_from_choices, required=True)
        def __init__(self, *args, **kwargs):
                user_id=kwargs.pop('user_id',0)
                super(searchForm, self).__init__(*args, **kwargs)
                uos_choices = [(o.unit_id, str(o.unit_id)) for o in UOS.objects.all()]
                print uos_choices
                if len(uos_choices) > 0:
                        self.fields['UoS'] = forms.ChoiceField(widget = forms.Select(), choices=uos_choices, required=True)

class tutorSubjectsForm(forms.Form):
        UoS = forms.ChoiceField(label="Unit of Study")
        is_tutoring = forms.BooleanField(label="I want to tutor for this UoS")
        price = forms.IntegerField(label="Price To ($)", required=False)
        def __init__(self, *args, **kwargs):
                user_id=kwargs.pop('user_id',0)
                super(tutorSubjectsForm, self).__init__(*args, **kwargs)
                uos_choices = [(o.unit_id.unit_id, str(o.unit_id.unit_id)) for o in UnitDetails.objects.filter(user_id__id = int(user_id))]
                print uos_choices
                if len(uos_choices) > 0:
                        self.fields['UoS'] = forms.ChoiceField(widget = forms.Select(), choices=uos_choices, required=True)
        
 
class LocationForm (ModelForm):
        class Meta:
                model = Location

class TutorLocationForm (ModelForm):
        class Meta:
                model = TutoringLocation

templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

    <head>
        <link rel="icon" href="{{STATIC_URL}}tutablr/img/favicon.ico">
        <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="{{STATIC_URL}}tutablr/css/general.css" />
        {% block extra_head %} {% endblock %}
        <title>{% block title %}Tutablr{% endblock %}</title>
    </head>

    <body class="well" {% block body_attributes%}{%endblock%}>
         <div id="main-container" class="container-fluid">
                    <div class="row-fluid">
                        <div id="logo" class="span3">
                            <img src="{{STATIC_URL}}tutablr/img/logo.png" alt="Logo"  />
                        </div>
                        <div id="login-div">
                                        {%block top-form %}{% endblock %}  {# This is the area for the login box or login information if the user is logged in #}
                        </div>
                        
                    </div>       
                    <div id="logged-out-nav" class="navbar"> 
                        <div class="navbar-inner">
                        {% block navigation-bar %} {# Navigation Bar #}
                            <ul class="nav">
                                <li><a href="/">Home</a></li>
                                <li><a href="/accounts/register">Register As Tutor</a></li>
                                <li><a href="/howitworks">How TuTablr Works</a></li>
                            </ul>
                        {% endblock %}
                        </div>
                    </div>  



                    <div id="main-area" class="row-fluid">
                        {% block content %}
                            <p>MAIN AREA</p>
                        {% endblock %}
                    </div>
        </div>
        <footer class="footer">
            <div class="container">
                {% block footer %}
                <p id="footer-text">&copy; Lolcatz IT</p>
                {% endblock %}
            </div>
        </footer>
        {% block usual_scripts %}
        {% block jquery %}<script src="{{STATIC_URL}}tutablr/js/jquery-1.8.2.min.js"></script>{% endblock%}
        <script src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
        <script src="{{STATIC_URL}}tutablr/js/general_functions.js"></script>
        {% endblock %}
        {% block extra_scripts %} {% endblock %}
    </body>

</html>

templates/base_logged_out.html
{% extends "base.html" %}{# This template is used to show the login box on the pages #}
{% load i18n %}

{% block top-form %}
    {% load widget_tweaks %}
    <form id="login-form"  class="form span3 offset6" method="post"  action="/login">{% csrf_token %}
        {% if user.is_authenticated %}
            <img id="usyd-logo_id"src="{{STATIC_URL}}tutablr/img/usyd-logo.jpg" alt="usyd-logo" width="70" height="60">
            <div id="logged-in-text">
                <p id="welcome_id">Welcome {{ user.username }} </p>
                <div id="login-links">
                    <a id="logout-btn"href="#">{% trans "Logout" %}</a>  |
                    <a href="/dashboard">{% trans "My Dashboard" %}</a>                     
                </div>

            </div>
        {% else %}
            <div id="login-input">
                     {{ form.username|append_attr:"class:input-small"|append_attr:"placeholder:Username" }}
                    {{ form.password|append_attr:"class:input-small"|append_attr:"placeholder:Password" }}
                    <button id="login-btn"type="submit">Log In</button>
                     <a id="reset-btn" href="{% url auth_password_reset %}">{% trans "Reset Password" %}</a>
            </div>
                                {{form.errors}}          
          <input type="hidden" name="next" value="{{ next }}" />

        {% endif %}
    </form>
{% endblock %}

templates/location.html
<html>
<head>
    <title>TEST LOCATION</title>
</head>
<body>
        <a href="locations/personal/edit"> Edit Personal Location</a>
        <a href="locations/tutoring/add" > Add Tutoring Location </a>
        <a href="#" title="">Edit Tutoring Locations</a>
</body>
</html>

templates/locationAdd.html
{% extends "base_logged_out.html" %}
{% load i18n %}

{% block content %}
    {{form.as_p}}
{% endblock %}

 {% block extra_head %}
    <link rel="stylesheet" href="{{STATIC_URL}}tutablr/css/contact.css" />
  {% endblock %}

{% block navigation-bar %} {# Navigation Bar #}
  <ul class="nav">
      <li ><a href="/">Home</a></li>
      <li><a href="/accounts/register">Register As Tutor</a></li>
      <li><a href="#">How TuTablr Works</a></li>
  </ul>
{% endblock %}

templates/location_edit_personal.html
{% extends "base_logged_out.html" %}
{% load i18n %}

{% block content %}

{% if form%}
  <div class="span4">
    <form action="/profile/locations/personal/edit" method="POST" accept-charset="utf-8">{% csrf_token %}
  <legend>Edit Preferred Location</legend>
  <span class="help-block">Example block-level help text here.</span>
       <label>Suburb</label>
        {{form.preferred_suburb}}
        <label>Longitude</label>
        {{form.longitude}}
        <label>Latitude</label>
        {{form.latitude}}
        <button type="submit"> Save </button>
  </div>
        <div id="maps" class="span8">
              <div id="map_canvas"></div>
              <input id="address" type="text" name="" value="" placeholder="Address">
              <button onclick="codeAddress()" id="submit" type="button">Geolocate</button>
        </div>
    </form>
{% else %}
  <p>{{response}}</p>

{%endif%}
{% endblock %}

{% block extra_scripts %} 
    <script src="{{STATIC_URL}}tutablr/js/gmaps_location.js"></script>
{% endblock %}

 {% block extra_head %}
    <link rel="stylesheet" href="{{STATIC_URL}}tutablr/css/location_personal.css" />
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXP-Ie48j28NaBt_x-4oVMaE3wpfY7t4s&sensor=true">
     </script>
  {% endblock %}

{% block navigation-bar %} {# Navigation Bar #}
  <ul class="nav">
      <li ><a href="/">Home</a></li>
      <li><a href="/accounts/register">Register As Tutor</a></li>
      <li><a href="#">How TuTablr Works</a></li>
  </ul>
{% endblock %}

{% block body_attributes%}
  onload="initialize()"
{%endblock%}

templates/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		{% extends "base_logged_out.html" %}
		{% load i18n %}

		{% block extra_head %}
		<link rel="stylesheet" href="{{STATIC_URL}}tutablr/css/dashboard.css" />
		{% endblock %}
		{% block content %}
		<meta name="generator" content="HTML Tidy for Windows (vers 14 February 2006), see www.w3.org" />
		<!--<script src="{{STATIC_URL}}tutablr/js/gmaps_location.js"></script>-->
		<!--<script type="text/javascript"
		src="http://maps.google.com/maps?file=api&amp;v=3&amp;key=AIzaSyA9sas6RsHsj-C82MfGafNtxn7tepWvsQo&sensor=true">
		</script>-->
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9sas6RsHsj-C82MfGafNtxn7tepWvsQo&sensor=false"></script>
		<script type="text/javascript">
			var infowindow;
			(function() {

				google.maps.Map.prototype.markers = new Array();

				google.maps.Map.prototype.addMarker = function(marker) {
					this.markers[this.markers.length] = marker;
				};

				google.maps.Map.prototype.getMarkers = function() {
					return this.markers
				};

				google.maps.Map.prototype.clearMarkers = function() {
					if (infowindow) {
						infowindow.close();
					}

					for (var i = 0; i < this.markers.length; i++) {
						this.markers[i].set_map(null);
					}
				};
			})();

			function initialize() {
				var latlng = new google.maps.LatLng(-33.8683, 151.2086);
				var myOptions = {
					zoom : 13,
					center : latlng,
					mapTypeId : google.maps.MapTypeId.ROADMAP
					//mapTypeId: google.maps.MapTypeId.SATELLITE
				};
				map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

				var a = new Array();
				var centered = false;
				{% if eligible_tutor_results %}

				{% for tutor in eligible_tutor_results %}
				if (parseFloat("{{tutor.latitude}}") != 0) {
					if (!centered) {
						map.setCenter(new google.maps.LatLng(parseFloat("{{tutor.latitude}}"), parseFloat("{{tutor.longitude}}")));
						centered = true;
					}

					var t = new Object();
					var rating = "N/A"
					if (parseFloat("{{tutor.rating}}") != 0) {
						rating = parseFloat("{{tutor.rating}}");
					}

					var contentString = '<div id={{tutor.username}}>' + '<h4 id="firstHeading" class="firstHeading">User: {{tutor.username}}</h4>' + '<p>Price: ${{tutor.price}}/hour</p>' + '<p>Average Rating: ' + rating + '</p>' + '<p>Distance: {{tutor.distance_in_kms}}kms</p>' + '<p><a href={{tutor.profile_url}}> Visit Profile</a></p>' + '<p><a href={{tutor.timetable_url}}>Make Booking</a></p>' + '</div>';
					t.name = contentString
					t.lat = parseFloat("{{tutor.latitude}}")
					t.lng = parseFloat("{{tutor.longitude}}")
					a.push(t);
				}
				{% endfor %}
				for (var i = 0; i < a.length; i++) {
					var latlng = new google.maps.LatLng(a[i].lat, a[i].lng);
					map.addMarker(createMarker(a[i].name, latlng));
				}
				console.log(map.getMarkers());

				console.log(map.getMarkers());
				{% endif %}
			}

			function createMarker(name, latlng) {
				var marker = new google.maps.Marker({
					position : latlng,
					map : map
				});
				google.maps.event.addListener(marker, "click", function() {
					if (infowindow)
						infowindow.close();
					infowindow = new google.maps.InfoWindow({
						content : name
					});
					infowindow.open(map, marker);
				});
				return marker;
			}

			function ratingString(rating) {
				if (parseFloat(rating) == 0) {
					return "N/A";
				} else {
					return rating + "/5";
				}
			}
		</script>
		<title></title>
	</head>
	<body onload="initialize()" onunload="GUnload()">
		<div id="tutor_search" title="Tutor Search">
			<form name="searchForm" action="/../../search/" method="post">
				{% csrf_token %}
				Unit of Study: {{ form.UoS }}
				Price From: {{ form.price_from }}
				Price To: {{ form.price_to }}
				<br>
				Distance: {{ form.distance}}
				Students Only: {{ form.students_only}}
				Rating From: {{ form.rating_from}}
				<br>
				<input class="datePicker" readonly="true" type="text" id="id_date" style="display:none" />
				<input type="submit" value="Find Tutors" id="SubmitAdd">
			</form>
		</div>
		<div id="map_canvas" style="width: 500px; height: 500px"></div>
		<div id="eligible_tutors" title="Eligible Tutors">
			{% if eligible_tutor_results %}
			<ul>
				{% for tutor in eligible_tutor_results %}
				<HR>
				Username: {{tutor.username}} | Price: ${{tutor.price}}/hour | Average Rating: {{tutor.rating}} | Distance: {{tutor.distance_in_kms}}kms | <a href={{tutor.timetable_url}}>Make a Booking</a> | <a href={{tutor.profile_url}}>View Tutor's Profile</a>
				{% endfor %}
				<HR>
			</ul>
			{% else %}
			<p>
				No tutors available.
			</p>
			{% endif %}

		</div>
		{% endblock %}
		{% block navigation-bar %} {# Navigation Bar #}
		<ul class="nav">
			<li>
				<a href="/dashboard">My Dashboard</a>
			</li>
			<li>
				<a href="/calendar">My Timetable</a>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Messages<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="/messages/inbox">Inbox</a>
					</li>
					<li>
						<a href="/messages/sent">Sent</a>
					</li>
					<li>
						<a href="/messages/archives/">Archive</a>
					</li>
					<li>
						<a href="/messages/trash">Trash</a>
					</li>
					<li>
						<a href="/messages/write">Write Message</a>
					</li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Settings<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="#">Edit Locations</a>
					</li>
					<li>
						<a href="#">Edit Tutorable Subjects</a>
					</li>
					<li>
						<a href="#">Add Review</a>
					</li>
					<li class="divider"></li>
					<li class="nav-header">
						My Profile
					</li>
					<li>
						<a href="#">View Profile</a>
					</li>
					<li>
						<a href="#">Edit Profile</a>
					</li>
				</ul>
			</li>
			<li>
				<a href="/search/">Find a Tutor</a>
			</li>
		</ul>
		{% endblock %}
	</body>
</html>